### ISSUE TITLE
Map vs Scan pooling

### ISSUE THREAD

**Issue by ivan-kleshnin** [rpominov/kefir#253]
```js
let xs = K.pool()
let ys = xs.map(x => x * 2)

xs.plug(K.constant(1))
xs.plug(K.constant(2))
xs.plug(K.constant(3))

ys.observe(console.log) // 2--4--6
```

3 events are emitted.

```js
let xs = K.pool()
let ys = xs.scan(x => x * 2, 1)

xs.plug(K.constant(1))
xs.plug(K.constant(2))
xs.plug(K.constant(3))

ys.observe(console.log) // 6
```

1 event is emitted.

This doesn't feel right. If pool queues values before the first subscription – both cases should emit 3 events. If pool keeps only the last value before subscription – why 3 events in the first case?

**Comment by rpominov** [comment]
This is because `scan` always produces a Property, which has a difference from Streams described in #142 .

You're right that this feels wrong. I'm not sure how to fix this properly though. Options are:

1. Change `scan` so it would create a Stream if source is a Stream (breaking change)
1. Do #142 (breaking change)
1. Add `toStream` method, that would work like `changes`, but keep "current" values (And also recover current values consumed by Properties somehow? Not sure this is even possible)

None of these solution seem 100% right and noncontroversial to me. Sometimes I think the core conceptual problem is Properties. I mean maybe overall semantics of the library would be more solid and consistent if we simply had only Streams.

Also I should mention that having multiple "current" values is not recommended anyway. You may have other issues with such pattern. I'd try to avoid it.

**Comment by ivan-kleshnin** [comment]
> None of these solution seem 100% right and noncontroversial to me.

Yes, reading those issues, I see what you mean. 

> I mean maybe overall semantics of the library would be more solid and consistent if we simply had only Streams.

I guess it would depend on how often `Properties` are used. In RxJS I use `.shareReplay(1)` only for state observables which are rare in comparison. XStream, meanwhile, reinvented the same property concept as `MemoryStream`. Intuitively, it seems it's just a matter of adding a single operator like https://github.com/mostjs/hold but I may be wrong here.

**Comment by rpominov** [comment]
Yeah, a simple operator like `hold` sounds like something that may work better that our current Properties semantics. But if we change that it'll be very painful for people to migrate their code bases. So I consider this more like a theoretical discussion at this point :)

**Comment by ivan-kleshnin** [comment]
I understand. Maybe like an idea for Kefir 4.x, for the future.
I'll close this issue then, because it's not unique. A note for possible readers who still don't get it:

**You should `observe` before pushing values to streams synchronously**
